// Bundles the static dashboard template + rendering JS into a plain JS module
// (as JSON-escaped strings) so they ship in the serverless function bundle
// without any runtime filesystem access. dashboard_js_full.txt contains many
// `${...}` JS template-literal expressions of its own, so it CANNOT be
// embedded via a JS template literal in another file (the outer literal would
// try to evaluate those expressions at the wrong time/scope) - JSON.stringify
// escaping avoids that entirely.
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const templatePart1 = fs.readFileSync(path.join(root, "vendor", "dashboard_template_part1.txt"), "utf8");
const dashboardJsFull = fs.readFileSync(path.join(root, "vendor", "dashboard_js_full.txt"), "utf8");
const pipelineBrowserJs = fs.readFileSync(path.join(root, "vendor", "ntp_pipeline_browser.js"), "utf8");

const out = `// AUTO-GENERATED by scripts/generate-assets.js - do not edit by hand.
module.exports = {
  templatePart1: ${JSON.stringify(templatePart1)},
  dashboardJsFull: ${JSON.stringify(dashboardJsFull)},
  pipelineBrowserJs: ${JSON.stringify(pipelineBrowserJs)},
};
`;

fs.writeFileSync(path.join(root, "lib", "assets.generated.js"), out);
console.log("Generated lib/assets.generated.js (" + out.length + " bytes)");
